name: VPS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup RDP
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install xrdp
        sudo systemctl enable xrdp
        sudo apt -y install xfce4 xfce4-terminal
        sudo sed -i.bak '/fi/a #xrdp multiple users configuration\n xfce-session \n' /etc/xrdp/startwm.sh
        sudo ufw allow 3389/tcp
        sudo systemctl start xrdp
        echo "RDP setup complete"
        
    - name: Create Tunnel
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo docker run --rm -i --net=host --privileged --name ngrok dannixon/armeabi-ngrok:latest ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        sudo docker run --rm -i --net=host --privileged --name ngrok dannixon/armeabi-ngrok:latest ngrok tcp 3389
